srobo/runbook

LICENSE
README.md
mkdocs.yml

This is the license which much of our documentation is already under and didn't appear to meet with any objections when proposed.
Discussion at https://github.com/srobo/tasks/issues/54.
Fixes https://github.com/srobo/runbook/issues/3.

Add Creative Commons license

---

.editorconfig
.gitattributes

This is intended to help ensure some consistency within our content.

Add editorconfig and gitattributes files

---

docs/competition/team-support/tinker-time.md

This is an attempt at documenting how Tinker Time works at a competition. This is based on how we have run things in the past, with some small tweaks

Add information about Tinker Time

---

docs/competition/matches/shepherding.md

This will close https://github.com/srobo/tasks/issues/114

Update shepherding roles and documentation

---

docs/competition/event/incident-management.md

This fixes https://github.com/srobo/tasks/issues/254

Add procedure for handling an incident occuring

---

docs/kit/hardware/kit-collation.md
docs/kit/hardware/kit-packing.md

A couple of small fixes to the kit hardware docs.

Improve kit docs

---

docs/competition/arena/README.md
docs/competition/matches/judging.md
docs/competition/matches/match-scoring.md
docs/competition/matches/shepherding.md
docs/competition/production/roles/network-manager.md

This adds various suggestions based on feedback from SR2019. None of this is expected to be particularly controversial and I've tried to frame each as a suggestion with some context as to where it came from, so that future readers can make their own decisions. I've not encountered any feedback which contradicts anything already in the runbook, which made this fairly easy :)

Add suggestions based on SR2019 feedback

---

docs/competition/teams/process-docs/overnight-battery-loan.md

Fixes https://github.com/srobo/tasks/issues/213

Add overnight battery loan docs

---

docs/volunteering/git-and-github.md

This is mostly recording the processes which the Core Team adopted last year.

Add some words about git & GitHub

---

docs/volunteering/communication-platforms.md

This repo exists, and is how people should be sending announcement emails. We should document its existence!

Document the existence of the `volunteer-emails` repo

---

docs/volunteering/internal-teams-guidance.md

This is a lightly modified version of the things I posted before at https://github.com/srobo/runbook/issues/52#issuecomment-502394587.
Fixes https://github.com/srobo/runbook/issues/52.

Add some guidance for internal teams

---

docs/volunteering/calendars.md

Document the calendars we use

---

docs/competition/livestream/README.md
docs/competition/livestream/matches.md
docs/competition/livestream/scenes.md

Fixes https://github.com/srobo/tasks/issues/660
Requested review from anyone who may have been involved with running a livestreamed event, how we run things, and how OBS may be setup.
I don't think there are any obvious omissions with regards to sections. Note that the intention of this PR is to document how it's done now, rather than be a channel for discussion of improvements. Those should happen elsewhere, however are greatly encouraged.

Add some docs on our livestream setup

---

docs/competition/virtual-competitions/README.md
docs/competition/virtual-competitions/competition-session-checklist.md

Also add some brief notes about Virtual Competitions.
Will close https://github.com/srobo/tasks/issues/659

Add a Virtual Competition Session Checklist

---

docs/competition/livestream/README.md

Fixes https://github.com/srobo/tasks/issues/664

Mention audio normalizing

---

docs/competition/livestream/scenes.md

Fixes https://github.com/srobo/tasks/issues/650

Mention that when cropping, it's better to aim for side-by-side cams over above

---

docs/competition/virtual-competitions/competition-session-checklist.md

Closes https://github.com/srobo/tasks/issues/656

Set a start time for volunteers on day of livestream

---

docs/README.md

This documents what was originally envisioned for the runbook.

Document the envisioned content approach and ownership model

---

docs/volunteering/glossary.md

We've found ourselves using the acronym KLI frequently for this, probably best to document it somewhere.

Add definition of KLI to glossary

---

mkdocs.yml

Have the edit links actually edit content

---

docs/kit/software/README.md

Replace ALARM specific info with Yocto

---

docs/infrastructure/README.md
docs/infrastructure/requesting-infrastructure.md

This includes guidance on who to request infrastructure from as well as how to do so.
Fixes https://github.com/srobo/infrastructure-team-minutes/issues/14

Add docs on requesting infrastructure

---

docs/infrastructure/operations.md
docs/infrastructure/requesting-infrastructure.md

This includes a proposal for an "on call" service at events.
@srobo/infrastructure-team it would be great to get your thoughts on this wording before we open this to other teams.
This builds on #137 so it can reference/extend those docs.
Fixes https://github.com/srobo/infrastructure-team-minutes/issues/6

Add Infrastructure Team SLOs

---

docs/kit/logistics/README.md
docs/kit/logistics/asset-tracking.md
docs/kit/logistics/kit-transport.md
docs/kit/logistics/logistics-software.md
docs/kit/logistics/research.md
docs/kit/logistics/transport/packaging.md

First in a series of PRs reviewing this section.

kit/logistics: Replace many references to Kit Logitics Coordinator

---

docs/kit/hardware/kit-debugging.md

this appears to work in docs/kit/event-operations/battery-charging.md

Use 4-space indent for nested list

---

docs/volunteering/glossary.md

From https://github.com/srobo/runbook/pull/152#issuecomment-1097168658

Improve the definition of a Doing by providing examples

---

docs/kit/event-operations/battery-charging.md

Based on feedback from Surrey Fire & Rescue Service

Update instructions on how to deal with a fire-y LiPo

---

docs/competition/team-support/battery-shuffler.md

- Remove Sunday evening battery shuffling
- Don't mention the Arrivals desk

Update battery shuffler docs for SR2022

---

docs/volunteering/glossary.md

These were initialisms we needed to explain to new volunteers

Add definitions for TLA and RUB

---

.spelling
docs/volunteering/glossary.md

I have had several people ask me what both of these terms are recently and as they are initialisms I think it would make sense to add them to our glossary.

Add definition of KCH and PLOD to glossary.

---

docs/infrastructure/machine-setup.md

This is a relatively high level guide and isn't aiming to reproduce e.g: https://github.com/srobo/server-puppet/blob/master/new-machine.md
Review mostly to check I've not missed anything.
I'll probably merge this in a week or so if there's no blockers and we can iterate from there.
Fixes https://github.com/srobo/runbook/issues/178
Fixes https://github.com/srobo/tasks/issues/897 (by documenting that we should do that ongoing)

Document machine setup in Mythic

---

docs/competition/volunteers/refreshments.md

Update refreshments for SR2023. This also includes using slightly less formal wording to make it easier to read.

Update refreshments role for SR2023

---

docs/competition/matches/match-scoring.md

Mention helpdesk tickets for score entry. I'm explicitly not mentioning how or when marshals make notes, because I need to check with Alistair, and that'll likely be a separate PR.

Mention helpdesk tickets for score entry

---

.spelling
docs/infrastructure/sending-emails.md

Fixes https://github.com/srobo/infrastructure-team-minutes/issues/18
We send emails very often, but don't have canonical documentation for how to do it properly.

Document how to send public emails

---

docs/programme/challenges.md

This information was pulled from the [`#challenge-judging-24`](https://studentrobotics.slack.com/archives/C062467Q0F7) channel

Document challenge submission and judging process

---

docs/volunteering/all-committees-meeting.md

Fixes https://github.com/srobo/committee-tasks/issues/17

Add committee meeting details

---

docs/competition/team-support/tinker-time.md

Related: https://github.com/srobo/tasks/issues/1451

Improve tinker time and test arena docs

---

docs/competition/team-support/helpdesk.md
docs/competition/team-support/kit-return.md
docs/competition/team-support/overnight-battery-loan.md
docs/competition/teams/role-descriptions/reception.md

Partially fixes https://github.com/srobo/tasks/issues/1407
Fixes https://github.com/srobo/tasks/issues/1409

Update helpdesk docs for SR2025

---

docs/competition/team-support/regulations-inspector.md

There's now a document to track the exemptions, it just needs mentioning.

Mention rules exemption document

---

docs/kit/logistics/kit-testing/test-procedures.md

Small correction to allow the generated CSV to be processed.

Remove the null character from the serial number
