srobo/runbook

- mkdocs.yml
The text is, I believe, sufficient. Not having the image is also lighter weight on the page-load, avoids styling munging and IMO looks better. I thought the button would look nice when I added it, but now I think I was wrong.
> Remove the license image

- docs/competition/team-support/battery-shuffler.md
Only really 1 update:
Remove explicit details about having boxes, as we probably will have the blue RUBs, but I'm pretty sure we don't need to be that specific here.
> Update Battery Shuffler Role for SR2019

- docs/competition/teams/role-descriptions/kit-return.md
Fixes https://github.com/srobo/tasks/issues/115
I've intentionally _not_ encoded any location information for this years competition, so the documentation can remain year-agnostic. 
Primary changes:
- Reflow content. Headers are slightly nicer to visually grep than a single list
- Add special case for those leaving before end of competition.
> Update kit handback plan

- Pipfile.lock
Run `pipenv update` to update packages, in the hopes to close some open security issues.
(None of said issues relate to _users_, just build-time)
> Run `pipenv update` to close open security issues

- README.md
- docs/README.md
This fills out the root page with meta information about the runbook as well as including a brief summary in the root readme.
I'm not actually sure if the (hosted) homepage is the right place for this, but it feels like a useful place to start.
Fixes #23
> Add meta information

- README.md
- docs/README.md
- docs/volunteering/glossary.md
This reflects the recent renaming of the Competition Team and that the Kit Team is now present in the latest published version.
> Update links to the teams within the ops-manual

- mkdocs.yml
Replaces #64
Requires https://github.com/srobo/website/pull/192
Partially fixes https://github.com/srobo/runbook/issues/17
Partially fixes https://github.com/srobo/runbook/issues/58
This allows the runbook to be accessed via `studentrobotics.org/runbook/`, which is nicer and easier to find. It also matches the regular pattern of hosting things as paths rather than subdomins, which matches 99% of everything else we do.
This changes the URLs generated, so the previous domain will still work, but any and all links will be redirected back to this primary url
> Host runbook at path on primary domain

- Pipfile
- Pipfile.lock
Also remove dependency on `pymdown-extensions`, so it's handled by the underlying package which requires it (the theme).
Replaces #67, in a less intrusive way. Turns out this issue also prevented us installing things, as it did a full update of all dependencies, which sucked!
I forget exactly why I pinned everything to `*`, but now this shouldn't happen again.
> Pin deps to versions specified in lockfile

- docs/volunteering/tasks.md
The tasks repo has some labels (https://github.com/srobo/tasks/labels) which have prefixes to categorize them. This was previously undocumented.
> Add section about task repo labels and what they mean

- Pipfile.lock
Achieved by running `pipenv lock` and then only adding the relevant parts.
This aims to fix the CI issue seem on #89.
> mkdocs-mermaid-plugin needs Beautifulsoup

- docs/competition/livestream/README.md
- docs/competition/livestream/matches.md
- docs/competition/virtual-competitions/competition-session-checklist.md
This removes the need to re-encode the videos as WebM and is another piece of software to setup as part of the livestream.
> We use Mixtape for Virtual Competition livestreams now

- .circleci/config.yml
Broken in #115 
Previously, the entire virtualenv was cached. Now we're only caching the pip cache, so we need to re-install the packages before they're available to use
> Install dependencies when deploying

- mkdocs.yml
- requirements.txt
See https://github.com/pugong/mkdocs-mermaid-plugin/issues/5, in particular https://github.com/pugong/mkdocs-mermaid-plugin/issues/5#issuecomment-613945139, which resulted in https://github.com/fralau/mkdocs-mermaid2-plugin.
The latter has more activity and appears to have resolved some of the known issues with the previous plugin.
> Move to a supported version of the mermaid plugin

- docs/teams/mentoring.md
This updates this document to reflect the approximate process used during the SR2021 cycle. This is broadly similar to the previous approach, though is much more open (notably using by default Slack rather than person-to-person emails) and supports remote mentoring.
This document now also contains much more information intended for the (potential) mentors rather than focussing entirely on the coordinator.
Fixes https://github.com/srobo/runbook/issues/99
See also https://github.com/srobo/volunteer-emails/pull/43 which adds the example email which this PR is removing.
> Rewrite the mentoring docs based on SR2021 experiences

- docs/infrastructure/README.md
- docs/infrastructure/competitor-services.md
This is deliberately fairly high level and I expect that it will probably remain relatively high level in favour of having detailed instructions closer to the code which actually controls the relevant setups.
> Add a summary of our general Tech Infrastructure

- docs/volunteering/glossary.md
- docs/volunteering/srawn.md
- Fixes #94
- Adds glossary entry for SR(A)WN
- Add SR(A)WN page to volunteering section
- Subscription info for SR(A)WN
- SR(A)WN production process
> volunteering: Add information about SR(A)WN

- docs/kit/logistics/kit-loan-extension.md
- docs/kit/logistics/kit-return.md
- docs/kit/logistics/transport/procedures.md
Document the process for kit return / kit loan extension.
Related to https://github.com/srobo/tasks/issues/452 and https://github.com/srobo/tasks/issues/451
Note: This PR is meant to reflect how it was done in SR2019, rather than how it should be done / will be done for SR2020. Changes for that should come in a separate PR.
> Document kit return

- requirements.txt
Until we can upgrade mkdocs (#124 or #122) we're somewhat stuck with pinning old versions when things break.
> Pin more package versions we need

- docs/kit/event-operations/battery-charging.md
This was done in the absence of a charger, hence vagueness. Is currently more of a reminder that it needs to be done.
> Add vague instructions on discharging batteries

- docs/kit/event-operations/battery-charging.md
The markdown library we're using appears to need newlines before lists in order for them to display correctly.
> Whitespace fixes to ensure proper layout

- docs/volunteering/offboarding-checklist.md
This is likely very incomplete, however provides a place for us to start adding things as we discover them.
The scope here is really the checklist of services, so it is explicitly _not_ the scope of this PR to make this checklist a complete guide for offboarding. (That would be great to do, but separately).
Fixes https://github.com/srobo/infrastructure-team-minutes/issues/12
> Add the start of an offboarding checklist

- docs/competition/event/incident-management.md
The head judge should be a role of adjudication not organisation. Head shepherd and the lead of event tech (lighting, construction, etc.) are better placed to assess an incident.
> Alternate roles for stopping the competition

- docs/infrastructure/machine-setup.md
- docs/infrastructure/security.md
Mostly so that we can record a policy on using multi-factor authentication.
Also mentions server security, copying & linking content from where this was already covered.
PR for visibility before adopting this policy more formally.
> Add an initial page on Information Security

- docs/programme/area-owners.md
Specifically:
* For reasons mainly of workload, tech days move out of event logistics to teams;
* As we aren't doing physical Kickstarts, that part is dropped (it can be reädded if needs be);
* Pit rules is made explicitly part of Health & Safety.
> Rearrangements of areas

- docs/programme/area-owners.md
These aren't competition team competencies so let's make these roles explicit liaison roles rather than area owners, to Reflect Reality.
> Declare two roles as explicit liaisons

- docs/competition/teams/process-docs/team-no-show.md
In theory this could apply to other events as well, however it is most useful & impactful at the Competition.
Fixes https://github.com/srobo/tasks/issues/1213
> Document the process for teams which don't arrive at the Competition

- .github/workflows/main.yml
I've been using 18 for a while locally and that's been fine. Relying on CI to check if 22 is also fine.
> Bump NodeJS

- .github/workflows/main.yml
There's no need to limit the concurrency between one PR run and another, nor a PR run and main.
> Scope concurrency limits to branches

- .spelling
- docs/competition/event/sr2025-setup.md
This adds the setup plan for the SR2025 competition.
Roughly, it works as follows:
- Volunteers are split into teams, each with a named leader (who is ideally experienced with the tasks on the team's list)
- Event Logistics oversee the setup to ensure it runs smoothly
> Add SR2025 competition setup plan

- .github/workflows/main.yml
This based on that in the website & docs repos, which have this in place.
See e.g: https://github.com/srobo/docs/pull/593 and https://github.com/srobo/docs/pull/600
I realise that currently we're not pinning our full dependencies, which is probably not optimal here, though I don't think that's a blocker and we can easily add that on later.
> Add support for PR diff comments vs the deployed version

- docs/competition/competition-roles.md
- docs/competition/matches/README.md
- docs/competition/matches/shepherding.md
- docs/competition/team-support/helpdesk.md
- docs/competition/team-support/regulations-inspector.md
This year, regs and safety checks are handed separately:
- Safety checks are done first, and are required before a team gets a battery. These are done at Helpdesk (docs already in place)
- Regs checks are done by volunteers visiting teams, and use a hi-viz to mark teams which have passed.
Staging can use a hi-viz to identify passes, and revoke them easily should the robot fail.
> Expand docs on safety and regs checks
